### ISSUE TITLE
Turn off file deletion option in yokogawa to ome zarr

### ISSUE THREAD

**Issue by jluethi** [fractal-analytics-platform/fractal-tasks-core#441] opened 2023-06-26 06:51 UTC
We should include additional checks before we expose a file deletion option for raw files as in https://github.com/fractal-analytics-platform/fractal-tasks-core/blob/e2e55991ab740a30bc9f2639f1acf14c650ba77b/fractal_tasks_core/tasks/yokogawa_to_ome_zarr.py#L245

Also, for real workflows, I'd imagine users would want to archive the real data, not have it deleted by the system.

Thus, I'll make a quick PR to remove this option for the moment.

**Comment by tcompa** [comment] 2023-06-26 10:18
Duplicate of #442, closing.

**Closed by tcompa** 2023-06-26 10:18 UTC
